/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedSuperadminRouteRouteImport } from './routes/_authenticated/superadmin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAffiliationsRouteImport } from './routes/_authenticated/admin/affiliations'
import { Route as AuthenticatedAdminConductRouteImport } from './routes/_authenticated/admin/conduct'
import { Route as AuthenticatedAdminEscalationsRouteImport } from './routes/_authenticated/admin/escalations'
import { Route as AuthenticatedAdminMatchesRouteImport } from './routes/_authenticated/admin/matches'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminMosqueRouteImport } from './routes/_authenticated/admin/mosque'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedMemberProfileIdRouteImport } from './routes/_authenticated/member.$profileId'
import { Route as AuthenticatedSuperadminIndexRouteImport } from './routes/_authenticated/superadmin/index'
import { Route as AuthenticatedSuperadminAnalyticsRouteImport } from './routes/_authenticated/superadmin/analytics'
import { Route as AuthenticatedSuperadminAuditRouteImport } from './routes/_authenticated/superadmin/audit'
import { Route as AuthenticatedSuperadminFlagsRouteImport } from './routes/_authenticated/superadmin/flags'
import { Route as AuthenticatedSuperadminModerationRouteImport } from './routes/_authenticated/superadmin/moderation'
import { Route as AuthenticatedSuperadminMosqueAdminsRouteImport } from './routes/_authenticated/superadmin/mosque-admins'
import { Route as AuthenticatedSuperadminMosquesRouteImport } from './routes/_authenticated/superadmin/mosques'
import { Route as AuthenticatedSuperadminProfilesRouteImport } from './routes/_authenticated/superadmin/profiles'
import { Route as AuthenticatedSuperadminRequestsRouteImport } from './routes/_authenticated/superadmin/requests'
import { Route as AuthenticatedSuperadminSettingsRouteRouteImport } from './routes/_authenticated/superadmin/settings/route'
import { Route as AuthenticatedSuperadminUsersRouteImport } from './routes/_authenticated/superadmin/users'
import { Route as AuthenticatedSuperadminSettingsIndexRouteImport } from './routes/_authenticated/superadmin/settings/index'
import { Route as AuthenticatedSuperadminSettingsBrandingRouteImport } from './routes/_authenticated/superadmin/settings/branding'
import { Route as AuthenticatedSuperadminSettingsWorkflowRouteImport } from './routes/_authenticated/superadmin/settings/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminRouteRoute =
  AuthenticatedSuperadminRouteRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAffiliationsRoute =
  AuthenticatedAdminAffiliationsRouteImport.update({
    id: '/affiliations',
    path: '/affiliations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConductRoute =
  AuthenticatedAdminConductRouteImport.update({
    id: '/conduct',
    path: '/conduct',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEscalationsRoute =
  AuthenticatedAdminEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMatchesRoute =
  AuthenticatedAdminMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMosqueRoute =
  AuthenticatedAdminMosqueRouteImport.update({
    id: '/mosque',
    path: '/mosque',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMemberProfileIdRoute =
  AuthenticatedMemberProfileIdRouteImport.update({
    id: '/member/$profileId',
    path: '/member/$profileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminIndexRoute =
  AuthenticatedSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminAnalyticsRoute =
  AuthenticatedSuperadminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminAuditRoute =
  AuthenticatedSuperadminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminFlagsRoute =
  AuthenticatedSuperadminFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminModerationRoute =
  AuthenticatedSuperadminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminMosqueAdminsRoute =
  AuthenticatedSuperadminMosqueAdminsRouteImport.update({
    id: '/mosque-admins',
    path: '/mosque-admins',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminMosquesRoute =
  AuthenticatedSuperadminMosquesRouteImport.update({
    id: '/mosques',
    path: '/mosques',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminProfilesRoute =
  AuthenticatedSuperadminProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminRequestsRoute =
  AuthenticatedSuperadminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminSettingsRouteRoute =
  AuthenticatedSuperadminSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminUsersRoute =
  AuthenticatedSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperadminRouteRoute,
  } as any)
const AuthenticatedSuperadminSettingsIndexRoute =
  AuthenticatedSuperadminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminSettingsRouteRoute,
  } as any)
const AuthenticatedSuperadminSettingsBrandingRoute =
  AuthenticatedSuperadminSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedSuperadminSettingsRouteRoute,
  } as any)
const AuthenticatedSuperadminSettingsWorkflowRoute =
  AuthenticatedSuperadminSettingsWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedSuperadminSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/superadmin': typeof AuthenticatedSuperadminRouteRouteWithChildren
  '/browse': typeof AuthenticatedBrowseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/superadmin/settings': typeof AuthenticatedSuperadminSettingsRouteRouteWithChildren
  '/admin/affiliations': typeof AuthenticatedAdminAffiliationsRoute
  '/admin/conduct': typeof AuthenticatedAdminConductRoute
  '/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/mosque': typeof AuthenticatedAdminMosqueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/member/$profileId': typeof AuthenticatedMemberProfileIdRoute
  '/superadmin/analytics': typeof AuthenticatedSuperadminAnalyticsRoute
  '/superadmin/audit': typeof AuthenticatedSuperadminAuditRoute
  '/superadmin/flags': typeof AuthenticatedSuperadminFlagsRoute
  '/superadmin/moderation': typeof AuthenticatedSuperadminModerationRoute
  '/superadmin/mosque-admins': typeof AuthenticatedSuperadminMosqueAdminsRoute
  '/superadmin/mosques': typeof AuthenticatedSuperadminMosquesRoute
  '/superadmin/profiles': typeof AuthenticatedSuperadminProfilesRoute
  '/superadmin/requests': typeof AuthenticatedSuperadminRequestsRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/superadmin/settings/branding': typeof AuthenticatedSuperadminSettingsBrandingRoute
  '/superadmin/settings/workflow': typeof AuthenticatedSuperadminSettingsWorkflowRoute
  '/superadmin/settings/': typeof AuthenticatedSuperadminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/admin/affiliations': typeof AuthenticatedAdminAffiliationsRoute
  '/admin/conduct': typeof AuthenticatedAdminConductRoute
  '/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/mosque': typeof AuthenticatedAdminMosqueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/member/$profileId': typeof AuthenticatedMemberProfileIdRoute
  '/superadmin/analytics': typeof AuthenticatedSuperadminAnalyticsRoute
  '/superadmin/audit': typeof AuthenticatedSuperadminAuditRoute
  '/superadmin/flags': typeof AuthenticatedSuperadminFlagsRoute
  '/superadmin/moderation': typeof AuthenticatedSuperadminModerationRoute
  '/superadmin/mosque-admins': typeof AuthenticatedSuperadminMosqueAdminsRoute
  '/superadmin/mosques': typeof AuthenticatedSuperadminMosquesRoute
  '/superadmin/profiles': typeof AuthenticatedSuperadminProfilesRoute
  '/superadmin/requests': typeof AuthenticatedSuperadminRequestsRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/superadmin': typeof AuthenticatedSuperadminIndexRoute
  '/superadmin/settings/branding': typeof AuthenticatedSuperadminSettingsBrandingRoute
  '/superadmin/settings/workflow': typeof AuthenticatedSuperadminSettingsWorkflowRoute
  '/superadmin/settings': typeof AuthenticatedSuperadminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteRouteWithChildren
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/superadmin/settings': typeof AuthenticatedSuperadminSettingsRouteRouteWithChildren
  '/_authenticated/admin/affiliations': typeof AuthenticatedAdminAffiliationsRoute
  '/_authenticated/admin/conduct': typeof AuthenticatedAdminConductRoute
  '/_authenticated/admin/escalations': typeof AuthenticatedAdminEscalationsRoute
  '/_authenticated/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/mosque': typeof AuthenticatedAdminMosqueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/member/$profileId': typeof AuthenticatedMemberProfileIdRoute
  '/_authenticated/superadmin/analytics': typeof AuthenticatedSuperadminAnalyticsRoute
  '/_authenticated/superadmin/audit': typeof AuthenticatedSuperadminAuditRoute
  '/_authenticated/superadmin/flags': typeof AuthenticatedSuperadminFlagsRoute
  '/_authenticated/superadmin/moderation': typeof AuthenticatedSuperadminModerationRoute
  '/_authenticated/superadmin/mosque-admins': typeof AuthenticatedSuperadminMosqueAdminsRoute
  '/_authenticated/superadmin/mosques': typeof AuthenticatedSuperadminMosquesRoute
  '/_authenticated/superadmin/profiles': typeof AuthenticatedSuperadminProfilesRoute
  '/_authenticated/superadmin/requests': typeof AuthenticatedSuperadminRequestsRoute
  '/_authenticated/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/_authenticated/superadmin/settings/branding': typeof AuthenticatedSuperadminSettingsBrandingRoute
  '/_authenticated/superadmin/settings/workflow': typeof AuthenticatedSuperadminSettingsWorkflowRoute
  '/_authenticated/superadmin/settings/': typeof AuthenticatedSuperadminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/superadmin'
    | '/browse'
    | '/dashboard'
    | '/match'
    | '/onboarding'
    | '/pending'
    | '/profile'
    | '/requests'
    | '/superadmin/settings'
    | '/admin/affiliations'
    | '/admin/conduct'
    | '/admin/escalations'
    | '/admin/matches'
    | '/admin/members'
    | '/admin/mosque'
    | '/admin/settings'
    | '/member/$profileId'
    | '/superadmin/analytics'
    | '/superadmin/audit'
    | '/superadmin/flags'
    | '/superadmin/moderation'
    | '/superadmin/mosque-admins'
    | '/superadmin/mosques'
    | '/superadmin/profiles'
    | '/superadmin/requests'
    | '/superadmin/users'
    | '/admin/'
    | '/superadmin/'
    | '/superadmin/settings/branding'
    | '/superadmin/settings/workflow'
    | '/superadmin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/browse'
    | '/dashboard'
    | '/match'
    | '/onboarding'
    | '/pending'
    | '/profile'
    | '/requests'
    | '/admin/affiliations'
    | '/admin/conduct'
    | '/admin/escalations'
    | '/admin/matches'
    | '/admin/members'
    | '/admin/mosque'
    | '/admin/settings'
    | '/member/$profileId'
    | '/superadmin/analytics'
    | '/superadmin/audit'
    | '/superadmin/flags'
    | '/superadmin/moderation'
    | '/superadmin/mosque-admins'
    | '/superadmin/mosques'
    | '/superadmin/profiles'
    | '/superadmin/requests'
    | '/superadmin/users'
    | '/admin'
    | '/superadmin'
    | '/superadmin/settings/branding'
    | '/superadmin/settings/workflow'
    | '/superadmin/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/superadmin'
    | '/_authenticated/browse'
    | '/_authenticated/dashboard'
    | '/_authenticated/match'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending'
    | '/_authenticated/profile'
    | '/_authenticated/requests'
    | '/_authenticated/superadmin/settings'
    | '/_authenticated/admin/affiliations'
    | '/_authenticated/admin/conduct'
    | '/_authenticated/admin/escalations'
    | '/_authenticated/admin/matches'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/mosque'
    | '/_authenticated/admin/settings'
    | '/_authenticated/member/$profileId'
    | '/_authenticated/superadmin/analytics'
    | '/_authenticated/superadmin/audit'
    | '/_authenticated/superadmin/flags'
    | '/_authenticated/superadmin/moderation'
    | '/_authenticated/superadmin/mosque-admins'
    | '/_authenticated/superadmin/mosques'
    | '/_authenticated/superadmin/profiles'
    | '/_authenticated/superadmin/requests'
    | '/_authenticated/superadmin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/superadmin/'
    | '/_authenticated/superadmin/settings/branding'
    | '/_authenticated/superadmin/settings/workflow'
    | '/_authenticated/superadmin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/affiliations': {
      id: '/_authenticated/admin/affiliations'
      path: '/affiliations'
      fullPath: '/admin/affiliations'
      preLoaderRoute: typeof AuthenticatedAdminAffiliationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conduct': {
      id: '/_authenticated/admin/conduct'
      path: '/conduct'
      fullPath: '/admin/conduct'
      preLoaderRoute: typeof AuthenticatedAdminConductRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/escalations': {
      id: '/_authenticated/admin/escalations'
      path: '/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AuthenticatedAdminEscalationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/matches': {
      id: '/_authenticated/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AuthenticatedAdminMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mosque': {
      id: '/_authenticated/admin/mosque'
      path: '/mosque'
      fullPath: '/admin/mosque'
      preLoaderRoute: typeof AuthenticatedAdminMosqueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/member/$profileId': {
      id: '/_authenticated/member/$profileId'
      path: '/member/$profileId'
      fullPath: '/member/$profileId'
      preLoaderRoute: typeof AuthenticatedMemberProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/': {
      id: '/_authenticated/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AuthenticatedSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/analytics': {
      id: '/_authenticated/superadmin/analytics'
      path: '/analytics'
      fullPath: '/superadmin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperadminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/audit': {
      id: '/_authenticated/superadmin/audit'
      path: '/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof AuthenticatedSuperadminAuditRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/flags': {
      id: '/_authenticated/superadmin/flags'
      path: '/flags'
      fullPath: '/superadmin/flags'
      preLoaderRoute: typeof AuthenticatedSuperadminFlagsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/moderation': {
      id: '/_authenticated/superadmin/moderation'
      path: '/moderation'
      fullPath: '/superadmin/moderation'
      preLoaderRoute: typeof AuthenticatedSuperadminModerationRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/mosque-admins': {
      id: '/_authenticated/superadmin/mosque-admins'
      path: '/mosque-admins'
      fullPath: '/superadmin/mosque-admins'
      preLoaderRoute: typeof AuthenticatedSuperadminMosqueAdminsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/mosques': {
      id: '/_authenticated/superadmin/mosques'
      path: '/mosques'
      fullPath: '/superadmin/mosques'
      preLoaderRoute: typeof AuthenticatedSuperadminMosquesRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/profiles': {
      id: '/_authenticated/superadmin/profiles'
      path: '/profiles'
      fullPath: '/superadmin/profiles'
      preLoaderRoute: typeof AuthenticatedSuperadminProfilesRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/requests': {
      id: '/_authenticated/superadmin/requests'
      path: '/requests'
      fullPath: '/superadmin/requests'
      preLoaderRoute: typeof AuthenticatedSuperadminRequestsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/settings': {
      id: '/_authenticated/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof AuthenticatedSuperadminSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/users': {
      id: '/_authenticated/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminRouteRoute
    }
    '/_authenticated/superadmin/settings/': {
      id: '/_authenticated/superadmin/settings/'
      path: '/'
      fullPath: '/superadmin/settings/'
      preLoaderRoute: typeof AuthenticatedSuperadminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminSettingsRouteRoute
    }
    '/_authenticated/superadmin/settings/branding': {
      id: '/_authenticated/superadmin/settings/branding'
      path: '/branding'
      fullPath: '/superadmin/settings/branding'
      preLoaderRoute: typeof AuthenticatedSuperadminSettingsBrandingRouteImport
      parentRoute: typeof AuthenticatedSuperadminSettingsRouteRoute
    }
    '/_authenticated/superadmin/settings/workflow': {
      id: '/_authenticated/superadmin/settings/workflow'
      path: '/workflow'
      fullPath: '/superadmin/settings/workflow'
      preLoaderRoute: typeof AuthenticatedSuperadminSettingsWorkflowRouteImport
      parentRoute: typeof AuthenticatedSuperadminSettingsRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAffiliationsRoute: typeof AuthenticatedAdminAffiliationsRoute
  AuthenticatedAdminConductRoute: typeof AuthenticatedAdminConductRoute
  AuthenticatedAdminEscalationsRoute: typeof AuthenticatedAdminEscalationsRoute
  AuthenticatedAdminMatchesRoute: typeof AuthenticatedAdminMatchesRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminMosqueRoute: typeof AuthenticatedAdminMosqueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAffiliationsRoute: AuthenticatedAdminAffiliationsRoute,
    AuthenticatedAdminConductRoute: AuthenticatedAdminConductRoute,
    AuthenticatedAdminEscalationsRoute: AuthenticatedAdminEscalationsRoute,
    AuthenticatedAdminMatchesRoute: AuthenticatedAdminMatchesRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
    AuthenticatedAdminMosqueRoute: AuthenticatedAdminMosqueRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSuperadminSettingsRouteRouteChildren {
  AuthenticatedSuperadminSettingsBrandingRoute: typeof AuthenticatedSuperadminSettingsBrandingRoute
  AuthenticatedSuperadminSettingsWorkflowRoute: typeof AuthenticatedSuperadminSettingsWorkflowRoute
  AuthenticatedSuperadminSettingsIndexRoute: typeof AuthenticatedSuperadminSettingsIndexRoute
}

const AuthenticatedSuperadminSettingsRouteRouteChildren: AuthenticatedSuperadminSettingsRouteRouteChildren =
  {
    AuthenticatedSuperadminSettingsBrandingRoute:
      AuthenticatedSuperadminSettingsBrandingRoute,
    AuthenticatedSuperadminSettingsWorkflowRoute:
      AuthenticatedSuperadminSettingsWorkflowRoute,
    AuthenticatedSuperadminSettingsIndexRoute:
      AuthenticatedSuperadminSettingsIndexRoute,
  }

const AuthenticatedSuperadminSettingsRouteRouteWithChildren =
  AuthenticatedSuperadminSettingsRouteRoute._addFileChildren(
    AuthenticatedSuperadminSettingsRouteRouteChildren,
  )

interface AuthenticatedSuperadminRouteRouteChildren {
  AuthenticatedSuperadminSettingsRouteRoute: typeof AuthenticatedSuperadminSettingsRouteRouteWithChildren
  AuthenticatedSuperadminAnalyticsRoute: typeof AuthenticatedSuperadminAnalyticsRoute
  AuthenticatedSuperadminAuditRoute: typeof AuthenticatedSuperadminAuditRoute
  AuthenticatedSuperadminFlagsRoute: typeof AuthenticatedSuperadminFlagsRoute
  AuthenticatedSuperadminModerationRoute: typeof AuthenticatedSuperadminModerationRoute
  AuthenticatedSuperadminMosqueAdminsRoute: typeof AuthenticatedSuperadminMosqueAdminsRoute
  AuthenticatedSuperadminMosquesRoute: typeof AuthenticatedSuperadminMosquesRoute
  AuthenticatedSuperadminProfilesRoute: typeof AuthenticatedSuperadminProfilesRoute
  AuthenticatedSuperadminRequestsRoute: typeof AuthenticatedSuperadminRequestsRoute
  AuthenticatedSuperadminUsersRoute: typeof AuthenticatedSuperadminUsersRoute
  AuthenticatedSuperadminIndexRoute: typeof AuthenticatedSuperadminIndexRoute
}

const AuthenticatedSuperadminRouteRouteChildren: AuthenticatedSuperadminRouteRouteChildren =
  {
    AuthenticatedSuperadminSettingsRouteRoute:
      AuthenticatedSuperadminSettingsRouteRouteWithChildren,
    AuthenticatedSuperadminAnalyticsRoute:
      AuthenticatedSuperadminAnalyticsRoute,
    AuthenticatedSuperadminAuditRoute: AuthenticatedSuperadminAuditRoute,
    AuthenticatedSuperadminFlagsRoute: AuthenticatedSuperadminFlagsRoute,
    AuthenticatedSuperadminModerationRoute:
      AuthenticatedSuperadminModerationRoute,
    AuthenticatedSuperadminMosqueAdminsRoute:
      AuthenticatedSuperadminMosqueAdminsRoute,
    AuthenticatedSuperadminMosquesRoute: AuthenticatedSuperadminMosquesRoute,
    AuthenticatedSuperadminProfilesRoute: AuthenticatedSuperadminProfilesRoute,
    AuthenticatedSuperadminRequestsRoute: AuthenticatedSuperadminRequestsRoute,
    AuthenticatedSuperadminUsersRoute: AuthenticatedSuperadminUsersRoute,
    AuthenticatedSuperadminIndexRoute: AuthenticatedSuperadminIndexRoute,
  }

const AuthenticatedSuperadminRouteRouteWithChildren =
  AuthenticatedSuperadminRouteRoute._addFileChildren(
    AuthenticatedSuperadminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSuperadminRouteRoute: typeof AuthenticatedSuperadminRouteRouteWithChildren
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedMemberProfileIdRoute: typeof AuthenticatedMemberProfileIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSuperadminRouteRoute:
    AuthenticatedSuperadminRouteRouteWithChildren,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedMemberProfileIdRoute: AuthenticatedMemberProfileIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
